language: python

python:
    - "2.7"
    - "3.2"

before_script:
    - python setup.py flake8

script:
    - python setup.py test

after_success:
    - pip install coveralls
    - coveralls

branches:
  only:
    - master

notifications:
    email: false
